// Auto-generated by LCARS Designer for firmware-v2 — DO NOT EDIT
// Re-generate by saving/building in the designer
#pragma once

// ---- Screen 0: Claude.ai ----
#define V3_AI_5H_BAR_X  60
#define V3_AI_5H_BAR_Y  200
#define V3_AI_5H_BAR_W  294
#define V3_AI_5H_BAR_H  11
#define V3_AI_SEP_X  56
#define V3_AI_SEP_Y  220
#define V3_AI_SEP_W  304
#define V3_AI_SEP_COLOR  #FFAA00
#define V3_AI_7D_BAR_X  60
#define V3_AI_7D_BAR_Y  384
#define V3_AI_7D_BAR_W  294
#define V3_AI_7D_BAR_H  11

// ---- Screen 1: Status ----
#define V3_ST_NET_X  72
#define V3_ST_NET_Y  40
#define V3_ST_NET_FONT  LCARS_FONT_SM
#define V3_ST_NET_COLOR  #FFAA00
#define V3_ST_NET_DATUM  TL_DATUM
#define V3_ST_WIFI_X  72
#define V3_ST_WIFI_Y  56
#define V3_ST_WIFI_W  294
#define V3_ST_WIFI_COLOR  #99CCFF
#define V3_ST_RSSI_X  72
#define V3_ST_RSSI_Y  70
#define V3_ST_RSSI_W  294
#define V3_ST_RSSI_COLOR  #FFCC99
#define V3_ST_IP_X  72
#define V3_ST_IP_Y  84
#define V3_ST_IP_W  294
#define V3_ST_IP_COLOR  #FFCC99
#define V3_ST_SEP1_X  72
#define V3_ST_SEP1_Y  102
#define V3_ST_SEP1_W  294
#define V3_ST_SEP1_COLOR  #FFAA00
#define V3_ST_API_X  72
#define V3_ST_API_Y  108
#define V3_ST_API_FONT  LCARS_FONT_SM
#define V3_ST_API_COLOR  #FFAA00
#define V3_ST_API_DATUM  TL_DATUM
#define V3_ST_APIST_X  72
#define V3_ST_APIST_Y  124
#define V3_ST_APIST_W  294
#define V3_ST_APIST_COLOR  #99CCFF
#define V3_ST_FETCH_X  72
#define V3_ST_FETCH_Y  138
#define V3_ST_FETCH_W  294
#define V3_ST_FETCH_COLOR  #FFCC99
#define V3_ST_SEP2_X  72
#define V3_ST_SEP2_Y  156
#define V3_ST_SEP2_W  294
#define V3_ST_SEP2_COLOR  #FFAA00
#define V3_ST_SYS_X  72
#define V3_ST_SYS_Y  162
#define V3_ST_SYS_FONT  LCARS_FONT_SM
#define V3_ST_SYS_COLOR  #FFAA00
#define V3_ST_SYS_DATUM  TL_DATUM
#define V3_ST_UP_X  72
#define V3_ST_UP_Y  178
#define V3_ST_UP_W  294
#define V3_ST_UP_COLOR  #FFCC99
#define V3_ST_HEAP_X  72
#define V3_ST_HEAP_Y  192
#define V3_ST_HEAP_W  294
#define V3_ST_HEAP_COLOR  #FFCC99
#define V3_ST_CASCADE_X  72
#define V3_ST_CASCADE_Y  210
#define V3_ST_CASCADE_W  294
#define V3_ST_CASCADE_H  200

// ---- Screen 2: Setup ----
#define V2_SETUP_TITLE_X  219
#define V2_SETUP_TITLE_Y  50
#define V2_SETUP_TITLE_FONT  LCARS_FONT_MD
#define V2_SETUP_TITLE_COLOR  LCARS_AMBER
#define V2_SETUP_TITLE_DATUM  TC_DATUM
#define V2_SETUP_INSTR_X  219
#define V2_SETUP_INSTR_Y  80
#define V2_SETUP_INSTR_FONT  LCARS_FONT_SM
#define V2_SETUP_INSTR_COLOR  LCARS_ICE
#define V2_SETUP_INSTR_DATUM  TC_DATUM
#define V2_SETUP_AP_X  219
#define V2_SETUP_AP_Y  98
#define V2_SETUP_AP_FONT  LCARS_FONT_LG
#define V2_SETUP_AP_COLOR  LCARS_AMBER
#define V2_SETUP_AP_DATUM  TC_DATUM
#define V2_SETUP_OPEN_X  219
#define V2_SETUP_OPEN_Y  134
#define V2_SETUP_OPEN_FONT  LCARS_FONT_SM
#define V2_SETUP_OPEN_COLOR  LCARS_ICE
#define V2_SETUP_OPEN_DATUM  TC_DATUM
#define V2_SETUP_URL_X  219
#define V2_SETUP_URL_Y  152
#define V2_SETUP_URL_FONT  LCARS_FONT_MD
#define V2_SETUP_URL_COLOR  LCARS_AMBER
#define V2_SETUP_URL_DATUM  TC_DATUM

// ---- Frame Chrome ----
#define FRAME_SIGNAL_TEXT_X  140
#define FRAME_SIGNAL_TEXT_Y  430
#define FRAME_SIGNAL_TEXT_COLOR  LCARS_TEXT_DIM
#define FRAME_SIGNAL_TEXT_FONT  LCARS_FONT_LG
#define FRAME_SIGNAL_TEXT_TEXT  "SIGNAL"
#define FRAME_SIGNAL_BARS_X  152
#define FRAME_SIGNAL_BARS_Y  416
#define FRAME_COUNTDOWN_X  212
#define FRAME_COUNTDOWN_Y  412
#define FRAME_COUNTDOWN_W  124
#define FRAME_COUNTDOWN_H  29
#define FRAME_COUNTDOWN_COLOR  LCARS_AMBER
#define FRAME_CLAUDE_X  362
#define FRAME_CLAUDE_Y  17
#define FRAME_CLAUDE_COLOR  LCARS_BLACK
#define FRAME_CLAUDE_FONT  LCARS_FONT_14
#define FRAME_CLAUDE_TEXT  "CLAUDE.AI"
#define FRAME_PAGE_X  72
#define FRAME_PAGE_Y  413
#define FRAME_PAGE_W  28
#define FRAME_PAGE_H  34
#define FRAME_PAGE_COLOR  LCARS_PEACH

// ---- Data-Bound Elements ----
#include "data_bindings.h"
enum BoundElType { BTYPE_GAUGE = 0, BTYPE_BAR, BTYPE_TEXT };
struct BoundElement { int16_t x, y; int16_t w, h; BoundElType type; DataBinding bind; int16_t r; int16_t thk; uint8_t fontSize; };

static const BoundElement V3_BOUND_SCREEN_0[] = {
    { 276, 120, 0, 0, BTYPE_GAUGE, BIND_AI_5H_PCT, 63, 12, 18 },
    { 284, 300, 0, 0, BTYPE_GAUGE, BIND_AI_7D_PCT, 64, 12, 18 },
    { 64, 68, 0, 0, BTYPE_TEXT, BIND_AI_5H_CLOCK, 0, 0, 28 },
    { 68, 240, 0, 0, BTYPE_TEXT, BIND_AI_7D_CLOCK, 0, 0, 28 },
};
#define V3_BOUND_SCREEN_0_COUNT  4

