#!/usr/bin/env python3
"""
Convert Antonio.ttf to Adafruit GFX bitmap font C header files.
These fonts are used by Arduino_GFX_Library on boards without TFT_eSPI (e.g., ESP32-C6 AMOLED).

Usage:  python tools/create_gfx_fonts.py
Output: include/gfx_font_12.h, gfx_font_14.h, ..., gfx_font_36.h
"""

from PIL import Image, ImageDraw, ImageFont
import os, sys

FONT_PATH = os.path.join(os.path.dirname(__file__), "Antonio.ttf")
OUT_DIR   = os.path.join(os.path.dirname(__file__), "..", "include")

# ASCII printable range (space through tilde)
FIRST_CHAR = 32
LAST_CHAR  = 126
CHARS = [chr(c) for c in range(FIRST_CHAR, LAST_CHAR + 1)]


def render_glyph(font, char, ascent):
    """Render a single character and extract 1-bit bitmap + GFX metrics."""
    canvas_sz = ascent + 40

    # Render character in grayscale then threshold to 1-bit
    img = Image.new('L', (canvas_sz * 2, canvas_sz), 0)
    draw = ImageDraw.Draw(img)
    draw.text((10, 0), char, fill=255, font=font)

    # Find tight bounding box
    pixels = img.load()
    w_img, h_img = img.size
    left = top = None
    right = bottom = 0

    for py in range(h_img):
        for px in range(w_img):
            if pixels[px, py] > 127:  # threshold for 1-bit
                if left is None:
                    left = px
                    top = py
                left = min(left, px)
                right = max(right, px)
                top = min(top, py)
                bottom = max(bottom, py)

    xAdvance = int(round(font.getlength(char)))

    if left is None:
        # Empty glyph (space character)
        return {
            'width': 0, 'height': 0,
            'xAdvance': max(xAdvance, 1),
            'xOffset': 0, 'yOffset': 0,
            'bits': []
        }

    gw = right - left + 1
    gh = bottom - top + 1

    # Extract 1-bit bitmap (row-major, MSB first)
    bits = []
    for py in range(top, bottom + 1):
        for px in range(left, right + 1):
            bits.append(1 if pixels[px, py] > 127 else 0)

    # GFX metrics:
    # xOffset = left bearing relative to cursor
    # yOffset = top of glyph relative to baseline (negative = above baseline)
    xOffset = left - 10  # we drew at x=10
    yOffset = top - ascent  # negative means above baseline

    return {
        'width': gw, 'height': gh,
        'xAdvance': xAdvance,
        'xOffset': xOffset, 'yOffset': yOffset,
        'bits': bits
    }


def bits_to_bytes(bits):
    """Pack a list of 0/1 bits into bytes (MSB first), padding last byte."""
    result = []
    for i in range(0, len(bits), 8):
        byte = 0
        for j in range(8):
            if i + j < len(bits) and bits[i + j]:
                byte |= (1 << (7 - j))
        result.append(byte)
    return result


def generate_gfx_font(font_path, size):
    """Generate Adafruit GFX font data from a TTF font at given pixel size."""
    font = ImageFont.truetype(font_path, size)
    ascent, descent = font.getmetrics()

    glyphs = []
    for ch in CHARS:
        glyphs.append(render_glyph(font, ch, ascent))

    # Pack all glyph bitmaps into a single byte array
    bitmap_bytes = []
    glyph_entries = []

    for g in glyphs:
        offset = len(bitmap_bytes)
        packed = bits_to_bytes(g['bits'])
        bitmap_bytes.extend(packed)
        glyph_entries.append({
            'offset': offset,
            'width': g['width'],
            'height': g['height'],
            'xAdvance': g['xAdvance'],
            'xOffset': g['xOffset'],
            'yOffset': g['yOffset'],
        })

    yAdvance = ascent + descent

    return bitmap_bytes, glyph_entries, yAdvance


def write_gfx_header(bitmap_bytes, glyph_entries, yAdvance, size, out_path):
    """Write Adafruit GFX font as a C header file."""
    name = f"AntonioGFX{size}"

    lines = []
    lines.append("#pragma once")
    lines.append("#include <Arduino.h>")
    lines.append("")
    lines.append(f"// Antonio Regular {size}px - Adafruit GFX bitmap font")
    lines.append(f"// Generated by tools/create_gfx_fonts.py")
    lines.append(f"// Chars {FIRST_CHAR}-{LAST_CHAR}, bitmap {len(bitmap_bytes)} bytes")
    lines.append("")

    # Bitmap array
    lines.append(f"const uint8_t {name}Bitmaps[] PROGMEM = {{")
    for i in range(0, len(bitmap_bytes), 16):
        chunk = bitmap_bytes[i:i+16]
        hex_str = ", ".join(f"0x{b:02X}" for b in chunk)
        if i + 16 < len(bitmap_bytes):
            hex_str += ","
        lines.append(f"    {hex_str}")
    lines.append("};")
    lines.append("")

    # Glyph table
    lines.append(f"const GFXglyph {name}Glyphs[] PROGMEM = {{")
    for i, g in enumerate(glyph_entries):
        ch = chr(FIRST_CHAR + i)
        ch_display = ch if ch != '\\' else '\\\\'
        ch_display = ch_display if ch != "'" else "\\'"
        lines.append(f"    {{ {g['offset']:5d}, {g['width']:3d}, {g['height']:3d}, "
                     f"{g['xAdvance']:3d}, {g['xOffset']:4d}, {g['yOffset']:4d} }}"
                     f"{',' if i < len(glyph_entries) - 1 else ' '} "
                     f"// 0x{FIRST_CHAR + i:02X} '{ch_display}'")
    lines.append("};")
    lines.append("")

    # Font struct
    lines.append(f"const GFXfont {name} PROGMEM = {{")
    lines.append(f"    (uint8_t  *){name}Bitmaps,")
    lines.append(f"    (GFXglyph *){name}Glyphs,")
    lines.append(f"    0x{FIRST_CHAR:02X}, 0x{LAST_CHAR:02X}, {yAdvance}")
    lines.append("};")
    lines.append("")

    with open(out_path, 'w') as f:
        f.write("\n".join(lines))

    total_kb = (len(bitmap_bytes) + len(glyph_entries) * 6) / 1024
    print(f"  Wrote {out_path} ({total_kb:.1f} KB data)")


def main():
    if not os.path.exists(FONT_PATH):
        print(f"Error: Font not found at {FONT_PATH}")
        sys.exit(1)

    os.makedirs(OUT_DIR, exist_ok=True)

    sizes = [12, 14, 16, 18, 20, 22, 24, 26, 28, 36]

    print("Converting Antonio.ttf to Adafruit GFX bitmap fonts...")
    for size in sizes:
        bitmap_bytes, glyph_entries, yAdvance = generate_gfx_font(FONT_PATH, size)
        out = os.path.join(OUT_DIR, f"gfx_font_{size}.h")
        write_gfx_header(bitmap_bytes, glyph_entries, yAdvance, size, out)

    print(f"\nDone! {len(sizes)} GFX font headers generated in include/")


if __name__ == "__main__":
    main()
